config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'static_pages/home'
  get    '/login',           to: 'sessions#new'
  post   '/login',           to: 'sessions#create'
  delete '/logout',          to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
end

#signup_pathを使用した方が良いのか？
#get '/signup', to: 'users#new' && post '/signup', to: 'users#create'

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 6)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post-form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>投稿一覧</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center">
    <h1>Blog</h1>
    <p>いらっしゃいませ　ごゆっくり！</p>
    <div class="home-container-box">
      <p>
        <%= link_to "登録する？", new_user_path, class: "btn btn-outline-dark btn-lg" %>
        or <%= link_to "ログイン！", login_path, class: "btn btn-outline-dark btn-lg" %>
      </p>
    </div>
  </div>
<% end %>