config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'static_pages/home'
  get    '/login',           to: 'sessions#new'
  post   '/login',           to: 'sessions#create'
  delete '/logout',          to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
end

#signup_pathを使用した方が良いのか？
#get '/signup', to: 'users#new' && post '/signup', to: 'users#create'

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    # if ActiveModel::SecurePassword.min_cost
    #   cost = BCrypt::Engine::MIM_COST
    # else
    #   cost = BCrypt::Engine.cost
    # end
    BCrypt::Password.create(string, cost: cost)
  end

  # このメソッドだけでランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  # self.remember_tokenとすることで remember_token属性が設定できる
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  #アカウントを有効
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  #パスワード再設定の属性を設定
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定用のメールを送信
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrue
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # feedの定義
  def feed
    Post.where("user_id = ?", id)
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  #有効化トークンとダイジェストを作製および代入
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    #strong parameter
    @user = User.create(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "アカウントを有効にするには、送信したメールを確認してください"
      redirect_to(root_url)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "変更に成功しました！"
      redirect_to(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to(users_url)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    #正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    #管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "削除", user, method: :delete, data: { confirm: "本当に大丈夫ですか？" } %>
  <% end %>
</li>

app/views/users/create.html.erb
<h1>登録完了</h1>
<%= link_to "indexへ", users_path %>

app/views/users/destroy.html.erb
<div class="center">
  <div class="form-box">
    <h2>退会しました</h2>
    <%= link_to "ホームページへ戻る", root_url, class: "btn btn-outline-primary" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>変更</h1>
<div class="row">
  <div class="col-md-6 form-box">
  <%= form_for @user, url: user_path(@user), html: { method: :patch } do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label "お名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "メールアドレス" %>
      <%= f.text_field :email, class: 'form-control' %></p>

      <%= f.label "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %></p>

      <%= f.label "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <% end %>

      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank" rel="noopener">画像変更</a>
      </div>
      <div class="edit-btn">
        <input type="submit" value="変更する" class="btn btn-outline-primary">
      </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>ユーザーリスト</h1>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 form-box">
    <%= form_for @user, url: users_path(@user), html: { method: :post } do |f| %>

      <!-- エラーメッセージを表示する -->
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label "お名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "メールアドレス" %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-outline-primary btn-sm" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <div>
      <%= link_to "投稿する", new_post_path, class: 'btn btn-outline-primary' %>
    </div>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>投稿数 (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<h1>変更しました</h1>
<%= link_to "indexへ", users_path %>