config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'static_pages/home'
  get    '/login',           to: 'sessions#new'
  post   '/login',           to: 'sessions#create'
  delete '/logout',          to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
end

#signup_pathを使用した方が良いのか？
#get '/signup', to: 'users#new' && post '/signup', to: 'users#create'

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>&copy; T_S.</li>
      <li><%= link_to "ホーム", root_path %></li>
      <li><%= link_to "ヘルプ", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light">
  <a href="#" class="navbar-brand">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
                                 data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                 aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path %>
      </li>
      <li class="nav-item active">
        <%= link_to "記事一覧", posts_path %>
      </li>
      <li class="nav-item">
        <%= link_to "ユーザーリスト", users_path %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール",  current_user %></li>
            <li><%= link_to "ユーザー情報変更", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "投稿する", new_post_path %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", login_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <mata name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>